language: python

# command to install dependencies
install:
  - pip install -r requirements.txt

branches:
  only:
  - master

stages:
  - test

jobs:
  include:
    - stage: test
      script: pytest
