language: python

python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

branches:
  only:
  - master

stages:
  - test

jobs:
  include:
    - stage: test
      script: pytest
